#!/usr/bin/env bash
# installs nginx and set a default messasge , port 80 as a default

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
