#!/usr/bin/env bash
# Fixing server
sudo rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
pkill -SIGKILL -f "/usr/sbin/nginx"